var PDFPageProxy = {
  "getViewport": function () {},
  "render": function () {},
}
var PDFDocumentProxy = {
  "getPage": function () {},
}
var PDFJS = {
    "version": {},
    "build": {},
    "pdfBug": {},
    "VERBOSITY_LEVELS": {
        "errors": {},
        "warnings": {},
        "infos": {}
    },
    "OPS": {
        "dependency": {},
        "setLineWidth": {},
        "setLineCap": {},
        "setLineJoin": {},
        "setMiterLimit": {},
        "setDash": {},
        "setRenderingIntent": {},
        "setFlatness": {},
        "setGState": {},
        "save": {},
        "restore": {},
        "transform": {},
        "moveTo": {},
        "lineTo": {},
        "curveTo": {},
        "curveTo2": {},
        "curveTo3": {},
        "closePath": {},
        "rectangle": {},
        "stroke": {},
        "closeStroke": {},
        "fill": {},
        "eoFill": {},
        "fillStroke": {},
        "eoFillStroke": {},
        "closeFillStroke": {},
        "closeEOFillStroke": {},
        "endPath": {},
        "clip": {},
        "eoClip": {},
        "beginText": {},
        "endText": {},
        "setCharSpacing": {},
        "setWordSpacing": {},
        "setHScale": {},
        "setLeading": {},
        "setFont": {},
        "setTextRenderingMode": {},
        "setTextRise": {},
        "moveText": {},
        "setLeadingMoveText": {},
        "setTextMatrix": {},
        "nextLine": {},
        "showText": {},
        "showSpacedText": {},
        "nextLineShowText": {},
        "nextLineSetSpacingShowText": {},
        "setCharWidth": {},
        "setCharWidthAndBounds": {},
        "setStrokeColorSpace": {},
        "setFillColorSpace": {},
        "setStrokeColor": {},
        "setStrokeColorN": {},
        "setFillColor": {},
        "setFillColorN": {},
        "setStrokeGray": {},
        "setFillGray": {},
        "setStrokeRGBColor": {},
        "setFillRGBColor": {},
        "setStrokeCMYKColor": {},
        "setFillCMYKColor": {},
        "shadingFill": {},
        "beginInlineImage": {},
        "beginImageData": {},
        "endInlineImage": {},
        "paintXObject": {},
        "markPoint": {},
        "markPointProps": {},
        "beginMarkedContent": {},
        "beginMarkedContentProps": {},
        "endMarkedContent": {},
        "beginCompat": {},
        "endCompat": {},
        "paintFormXObjectBegin": {},
        "paintFormXObjectEnd": {},
        "beginGroup": {},
        "endGroup": {},
        "beginAnnotations": {},
        "endAnnotations": {},
        "beginAnnotation": {},
        "endAnnotation": {},
        "paintJpegXObject": {},
        "paintImageMaskXObject": {},
        "paintImageMaskXObjectGroup": {},
        "paintImageXObject": {},
        "paintInlineImageXObject": {},
        "paintInlineImageXObjectGroup": {},
        "paintImageXObjectRepeat": {},
        "paintImageMaskXObjectRepeat": {},
        "paintSolidColorImageMask": {},
        "constructPath": {}
    },
    "UNSUPPORTED_FEATURES": {
        "unknown": {},
        "forms": {},
        "javaScript": {},
        "smask": {},
        "shadingPattern": {},
        "font": {}
    },
    "UnsupportedManager": {
        "listen": function () {},
        "notify": function () {}
    },
    "isValidUrl": function () {},
    "shadow": function () {},
    "PasswordResponses": {
        "NEED_PASSWORD": {},
        "INCORRECT_PASSWORD": {}
    },
    "PasswordException": function () {},
    "UnknownErrorException": function () {},
    "InvalidPDFException": function () {},
    "MissingPDFException": function () {},
    "UnexpectedResponseException": function () {},
    "Util": function () {},
    "PageViewport": function () {},
    "createPromiseCapability": function () {},
    "createBlob": function () {},
    "createObjectURL": function () {},
    "maxImageSize": {},
    "cMapUrl": function () {},
    "cMapPacked": {},
    "disableFontFace": {},
    "imageResourcesPath": {},
    "disableWorker": {},
    "workerSrc": {},
    "disableRange": {},
    "disableStream": {},
    "disableAutoFetch": {},
    "postMessageTransfers": {},
    "disableCreateObjectURL": {},
    "disableWebGL": {},
    "disableFullscreen": {},
    "useOnlyCssZoom": {},
    "verbosity": {},
    "maxCanvasPixels": {},
    "openExternalLinksInNewWindow": {},
    "getDocument": function () {},
    "PDFDataRangeTransport": function () {},
    "Metadata": function () {},
    "AnnotationUtils": {
        "getHtmlElement": function () {}
    },
    "SVGGraphics": function () {}
}
